language: crystal
install:
  - gem install redis
  - shards install
  - redis-cli info
services:
  - redis-server
script:
  - crystal spec
  # Check if examples are compiling
  - crystal build examples/sidekiq.cr
  - crystal build examples/web.cr
