language: crystal
install:
  - gem install redis
  - shards install --ignore-crystal-version
  - redis-cli info
services:
  - redis-server
script:
  - crystal tool format --check
  - ./bin/ameba
  - crystal spec
  # Check if examples are compiling
  - crystal build examples/sidekiq.cr
  - crystal build examples/web.cr
